### ISSUE TITLE
这代码能跑在服务器上么

### ISSUE THREAD

**Issue by fabcz** [sqaiyan/netmusic-node#12]
首先项目在本地已经完美跑起来，感谢开源
后端小白问下，这份 node 代码能跑到服务器上，然后 localhost:3000 改成对应的 IP 或 域名来访问么

**Comment by Calvin1121** [comment]
可以～我在阿里云上跑起来了

**Comment by fabcz** [comment]
# @Calvin1121 我在腾讯云跑起来了，一旦 WebShell 断开连接 node 就断开了，有什么办法能保持一直运行不

**Comment by sqaiyan** [comment]
用pm2 @fabcz
