### ISSUE TITLE
这个是什么情况？执行直接这样

### ISSUE THREAD

**Issue by dengbaoling** [sqaiyan/netmusic-node#13]
C:\Users\Administrator\Desktop\项目\netmusic-node-master\netmusic-node-master>npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN netmusic@1.0.0 No repository field.

added 95 packages from 99 contributors in 5.502s

C:\Users\Administrator\Desktop\项目\netmusic-node-master\netmusic-node-master>node app.js
启动App

**Comment by sqaiyan** [comment]
这就是启动好了啊

**Comment by sos591258136** [comment]
我也是到了这个步骤  显示了：启动APP
但是访问http://localhost:3000/v1/fm  无法访问，直接访问http://localhost:3000  也是连接失败。
就像是没有启动一样
![image](https://user-images.githubusercontent.com/29125715/45137689-5a420e00-b1dc-11e8-852b-0c740399acdd.png)

**Comment by sos591258136** [comment]
然后我尝试着用自己的网易云手机账号登陆。出现报错，返回的res内只有errMsg这一个，没有code。
![image](https://user-images.githubusercontent.com/29125715/45137793-b4db6a00-b1dc-11e8-8874-5c71426529d7.png)

**Comment by sos591258136** [comment]
经过排查发现，你把端口号改成3008了！！！！！蓝瘦。。香菇。。而且还需要买域名映射内网。
好(tai)麻(shang)烦(qian)
