### ISSUE TITLE
登录不了，错误信息已截图

### ISSUE THREAD

**Issue by ruyuewangzi** [sqaiyan/netmusic-node#4]
你写的网易音乐小程序很好，对应的这个nodejs后台，也有很多值得学习地方。
但是目前还不能运行起来，具体原因想请教下你。
下面这个图是使用 WebStorm 调试 app.js 中 createWebAPIRequest 方法的截图，res是网易返回的响应，当前调用的接口是登录接口。

![tim 20170427213321](https://cloud.githubusercontent.com/assets/10432874/25485764/9a5e2ba4-2b91-11e7-9039-4adb5b94f7ef.png)

请看一下，能否知道大概的问题。

**Comment by sqaiyan** [comment]
没看懂你这个图啊，不知道你是怎么运行的，你可以node启动下这个js,浏览器里直接访问这个接口试试，我这是可以的
