### ISSUE TITLE
客户端api

### ISSUE THREAD

**Issue by lone1y-51** [sqaiyan/netmusic-node#5]
请问你找到pc客户端api的加密方式了吗？
pc客户端有些接口和web的加密不一样，只有一个加密参数param，看你的api里好像没有相关的接口

**Comment by sqaiyan** [comment]
不知道，有哪些pc的接口web上没有吗，web上还能看到参数，pc上知道加密方法猜参数又是个体力活。其他地方搜搜吧，貌似好像什么时候我发现有人说知道怎么加密的。记忆模糊/滑稽脸
